title: Mohak Goyal


markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Â© Neelkanth"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "index" 
 - name: "CV"
   link: "Resume.pdf"
 - name: "Contact"
   link: "contact"
 
